disabled windows testing

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -45,7 +45,9 @@ jobs:
             -DCMAKE_CXX_COMPILER=cl \
             -DARCH=x86-64 \
             -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" \
-            -DVCPKG_TARGET_TRIPLET="x64-windows-static"
+            -DVCPKG_TARGET_TRIPLET="x64-windows-static" \
+            -DCMAKE_GENERATOR_PLATFORM=x64 \
+            -DCMAKE_GENERATOR="Ninja"
           cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui -j12
   
       - uses: actions/upload-artifact@v4
@@ -55,18 +57,18 @@ jobs:
             build/lib/*
             build/bin/*
 
-      - name: Build tests
-        run: cmake --build build --target tests -j12
+      # - name: Build tests
+      #   run: cmake --build build --target tests -j12
 
-      - name: Run tests
-        run: ctest --output-on-failure --test-dir build/tests
+      # - name: Run tests
+      #   run: ctest --output-on-failure --test-dir build/tests
 
-      - name: Generate test report
-        uses: mikepenz/action-junit-report@v4
-        if: (success() || failure())
-        with:
-          check_name: "Windows test report"
-          report_paths: build/tests/reports/*.xml
+      # - name: Generate test report
+      #   uses: mikepenz/action-junit-report@v4
+      #   if: (success() || failure())
+      #   with:
+      #     check_name: "Windows test report"
+      #     report_paths: build/tests/reports/*.xml
 
   build-mac:
     name: "MacOS universal"
