vcpkg.json

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -49,9 +49,11 @@ jobs:
       - uses: actions/setup-python@v5
 
       - name: Install vcpkg dependencies
+        env: 
+          VCPKG_DEFAULT_TRIPLET: x64-windows-static
         uses: lukka/run-vcpkg@v11
         with:
-          runVcpkgFormatString: '[`install`, `curl pkgconf cairo libwebp`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `x64-windows-static`]'
+          vcpkgJsonGlob: '.github/vcpkg.json'
           runVcpkgInstall: true
 
       - name: Install Python dependencies
@@ -79,44 +81,44 @@ jobs:
             build/lib/*
             build/bin/*
 
-  build-mac:
-    name: "MacOS universal"
-    needs: check-headers
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install dependencies
-        run: | 
-          brew install --quiet curl
+  # build-mac:
+  #   name: "MacOS universal"
+  #   needs: check-headers
+  #   runs-on: macos-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Install dependencies
+  #       run: | 
+  #         brew install --quiet curl
           
-      - name: Build the library
-        shell: bash
-        run: |
-          mkdir build
-          cmake -B build -S . \
-            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12  
+  #     - name: Build the library
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -B build -S . \
+  #           -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
+  #           -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12  
   
-      - uses: actions/upload-artifact@v4
-        with:
-          name: macos-universal-binaries
-          path: |
-            build/lib/*
-            build/bin/*
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: macos-universal-binaries
+  #         path: |
+  #           build/lib/*
+  #           build/bin/*
 
-      - name: Build tests
-        run: cmake --build build --target tests -j12
+  #     - name: Build tests
+  #       run: cmake --build build --target tests -j12
 
-      - name: Run tests
-        run: ctest --output-on-failure --parallel 6 --repeat until-pass:3 --test-dir build/tests
+  #     - name: Run tests
+  #       run: ctest --output-on-failure --parallel 6 --repeat until-pass:3 --test-dir build/tests
 
-      - name: Generate test report
-        uses: mikepenz/action-junit-report@v4
-        if: (success() || failure())
-        with:
-          check_name: "MacOS test report"
-          report_paths: build/tests/reports/*.xml
+  #     - name: Generate test report
+  #       uses: mikepenz/action-junit-report@v4
+  #       if: (success() || failure())
+  #       with:
+  #         check_name: "MacOS test report"
+  #         report_paths: build/tests/reports/*.xml
 
   build-mac-gui:
     name: "${{ matrix.name }}"
@@ -149,14 +151,16 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Install vcpkg dependencies
-        uses: lukka/run-vcpkg@v11
-        with:
-          runVcpkgFormatString: '[`install`, `curl pkgconf cairo libwebp`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `${{ matrix.vcpkg_triplet }}`]'
-          runVcpkgInstall: true
-
       - name: Set Xcode version
         run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.XCODE_VER }}.app/Contents/Developer
+
+      - name: Install vcpkg dependencies
+        uses: lukka/run-vcpkg@v11
+        env:
+          VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet }}
+        with:
+          vcpkgJsonGlob: '.github/vcpkg.json'
+          runVcpkgInstall: true
 
       - name: Build the library
         run: |
@@ -184,80 +188,80 @@ jobs:
             build/lib/*
             build/bin/*
 
-  build-ubuntu:
-    name: ${{ matrix.name }}
-    needs: check-headers
-    runs-on: ${{ matrix.os }}
-    strategy: 
-      fail-fast: false
-      matrix:
-        include:
-          - os: ubuntu-latest
-            name: "Ubuntu latest with GCC"
-            c_compiler: gcc
-            cpp_compiler: g++
-            arch: x86-64
+  # build-ubuntu:
+  #   name: ${{ matrix.name }}
+  #   needs: check-headers
+  #   runs-on: ${{ matrix.os }}
+  #   strategy: 
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - os: ubuntu-latest
+  #           name: "Ubuntu latest with GCC"
+  #           c_compiler: gcc
+  #           cpp_compiler: g++
+  #           arch: x86-64
 
-          - os: ubuntu-22.04
-            name: "Ubuntu 22.04 with GCC"
-            c_compiler: gcc-10
-            cpp_compiler: g++-10
-            arch: x86-64
+  #         - os: ubuntu-22.04
+  #           name: "Ubuntu 22.04 with GCC"
+  #           c_compiler: gcc-10
+  #           cpp_compiler: g++-10
+  #           arch: x86-64
 
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install libcurl4-openssl-dev libcairo2-dev libgtk-3-dev libwebp-dev
-          if [ $BUILD_TYPE == 'Debug' ]; then
-            sudo apt-get install libdwarf-dev
-          fi
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install libcurl4-openssl-dev libcairo2-dev libgtk-3-dev libwebp-dev
+  #         if [ $BUILD_TYPE == 'Debug' ]; then
+  #           sudo apt-get install libdwarf-dev
+  #         fi
           
-      - name: Build the library (ubuntu latest)
-        if: matrix.os == 'ubuntu-latest'
-        shell: bash
-        run: |
-          mkdir build
-          cmake -B build -S . \
-            -DGUI=ON \
-            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
-            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
-            -DARCH=${{ matrix.arch }}
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui -j12
+  #     - name: Build the library (ubuntu latest)
+  #       if: matrix.os == 'ubuntu-latest'
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -B build -S . \
+  #           -DGUI=ON \
+  #           -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
+  #           -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
+  #           -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
+  #           -DARCH=${{ matrix.arch }}
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui -j12
 
-      - name: Build the GUI executables (${{ matrix.os }})
-        if: matrix.os != 'ubuntu-latest'
-        shell: bash
-        run: |
-          mkdir build
-          cmake -B build -S . \
-            -DGUI=ON \
-            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
-            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
-            -DARCH=${{ matrix.arch }}
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12
+  #     - name: Build the GUI executables (${{ matrix.os }})
+  #       if: matrix.os != 'ubuntu-latest'
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -B build -S . \
+  #           -DGUI=ON \
+  #           -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
+  #           -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
+  #           -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
+  #           -DARCH=${{ matrix.arch }}
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.os }}-binaries
-          path: |
-            build/lib/*
-            build/bin/*
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ${{ matrix.os }}-binaries
+  #         path: |
+  #           build/lib/*
+  #           build/bin/*
  
-      - name: Build tests
-        if: matrix.os == 'ubuntu-latest'
-        run: cmake --build build --target tests -j12
+  #     - name: Build tests
+  #       if: matrix.os == 'ubuntu-latest'
+  #       run: cmake --build build --target tests -j12
 
-      - name: Run tests
-        if: matrix.os == 'ubuntu-latest'
-        run: ctest --output-on-failure --parallel 6 --repeat until-pass:3 --test-dir build/tests
+  #     - name: Run tests
+  #       if: matrix.os == 'ubuntu-latest'
+  #       run: ctest --output-on-failure --parallel 6 --repeat until-pass:3 --test-dir build/tests
 
-      - name: Generate test report
-        uses: mikepenz/action-junit-report@v4
-        if: matrix.os == 'ubuntu-latest' && (success() || failure())
-        with:
-          check_name: "Ubuntu test report"
-          report_paths: build/tests/reports/*.xml
+  #     - name: Generate test report
+  #       uses: mikepenz/action-junit-report@v4
+  #       if: matrix.os == 'ubuntu-latest' && (success() || failure())
+  #       with:
+  #         check_name: "Ubuntu test report"
+  #         report_paths: build/tests/reports/*.xml
