update

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -11,145 +11,144 @@ env:
   VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
 
 jobs:
-  build:
-    name: ${{matrix.name}}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          # - os: ubuntu-latest
-          #   name: "Ubuntu latest with gcc"
-          #   c_compiler: gcc
-          #   cpp_compiler: g++
-          #   arch: x86-64
+  # build:
+  #   name: ${{matrix.name}}
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         # - os: ubuntu-latest
+  #         #   name: "Ubuntu latest with gcc"
+  #         #   c_compiler: gcc
+  #         #   cpp_compiler: g++
+  #         #   arch: x86-64
 
-          # - os: ubuntu-20.04
-          #   name: "Ubuntu 20.04 with gcc"
-          #   c_compiler: gcc-10
-          #   cpp_compiler: g++-10
-          #   arch: x86-64
+  #         # - os: ubuntu-20.04
+  #         #   name: "Ubuntu 20.04 with gcc"
+  #         #   c_compiler: gcc-10
+  #         #   cpp_compiler: g++-10
+  #         #   arch: x86-64
 
-          # - os: windows-latest
-          #   name: "Windows latest with msvc"
-          #   c_compiler: cl
-          #   cpp_compiler: cl
-          #   arch: x86-64
+  #         # - os: windows-latest
+  #         #   name: "Windows latest with msvc"
+  #         #   c_compiler: cl
+  #         #   cpp_compiler: cl
+  #         #   arch: x86-64
 
-          - os: macos-latest
-            name: "MacOS arm64 latest with clang"
-            c_compiler: $(brew --prefix llvm@15)/bin/clang
-            cpp_compiler: $(brew --prefix llvm@15)/bin/clang++
-            arch: x86-64
+  #         - os: macos-latest
+  #           name: "MacOS arm64 latest with clang"
+  #           c_compiler: $(brew --prefix llvm@15)/bin/clang
+  #           cpp_compiler: $(brew --prefix llvm@15)/bin/clang++
+  #           arch: x86-64
 
-    steps: 
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #   steps: 
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Install dependencies (ubuntu)
-        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'
-        run: |
-          sudo apt-get update
-          sudo apt-get install libcurl4-openssl-dev libcairo2-dev libgtk-3-dev libwebp-dev
+  #     - name: Install dependencies (ubuntu)
+  #       if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install libcurl4-openssl-dev libcairo2-dev libgtk-3-dev libwebp-dev
 
-      - name: Install dependencies (macos)
-        if: matrix.os == 'macos-latest'
-        run: brew install curl pkg-config cairo fontconfig bzip2 expat zlib libpng webp
+  #     - name: Install dependencies (macos)
+  #       if: matrix.os == 'macos-latest'
+  #       run: brew install curl pkg-config cairo fontconfig bzip2 expat zlib libpng webp
 
-      - name: Export GitHub Actions cache environment variables
-        if: matrix.os == 'windows-latest'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
-            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
+  #     - name: Export GitHub Actions cache environment variables
+  #       if: matrix.os == 'windows-latest'
+  #       uses: actions/github-script@v6
+  #       with:
+  #         script: |
+  #           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
+  #           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
 
-      - name: Setup Python env (windows)
-        if: matrix.os == 'windows-latest'
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
-        id: windows-python
+  #     - name: Setup Python env (windows)
+  #       if: matrix.os == 'windows-latest'
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.12'
+  #       id: windows-python
 
-      - name: Install dependencies (windows)
-        if: matrix.os == 'windows-latest'
-        run: |
-          vcpkg install curl pkgconf cairo libwebp --triplet x64-windows-static
-          pip install matplotlib numpy pyinstaller
+  #     - name: Install dependencies (windows)
+  #       if: matrix.os == 'windows-latest'
+  #       run: |
+  #         vcpkg install curl pkgconf cairo libwebp --triplet x64-windows-static
+  #         pip install matplotlib numpy pyinstaller
 
-      - name: Get number of cores
-        uses: SimenB/github-actions-cpu-cores@v2
-        id: cpu-cores
+  #     - name: Get number of cores
+  #       uses: SimenB/github-actions-cpu-cores@v2
+  #       id: cpu-cores
 
-      - name: Install libdwarf for debug build
-        if: (matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest') && env.BUILD_TYPE == 'Debug'
-        run: |
-          if [ ${{ matrix.os }} == 'macos-latest' ]; then
-            brew install libdwarf
-          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
-            sudo apt-get install libdwarf-dev
-          fi
+  #     - name: Install libdwarf for debug build
+  #       if: (matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest') && env.BUILD_TYPE == 'Debug'
+  #       run: |
+  #         if [ ${{ matrix.os }} == 'macos-latest' ]; then
+  #           brew install libdwarf
+  #         elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
+  #           sudo apt-get install libdwarf-dev
+  #         fi
 
-      - name: Build the library (windows, vcpkg)
-        if: matrix.os == 'windows-latest'
-        shell: bash
-        run: |
-          mkdir build
-          cmake -DGUI=ON -DBUILD_PLOT_EXE=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DARCH=${{ matrix.arch }} \
-                -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows-static" \
-                -S . -B build
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui
+  #     - name: Build the library (windows, vcpkg)
+  #       if: matrix.os == 'windows-latest'
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -DGUI=ON -DBUILD_PLOT_EXE=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DARCH=${{ matrix.arch }} \
+  #               -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows-static" \
+  #               -S . -B build
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui
 
-      - name: Build the library (ubuntu latest)
-        if: matrix.os == 'ubuntu-latest'
-        shell: bash
-        run: |
-          mkdir build
-          cmake -DGUI=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DARCH=${{ matrix.arch }} -S . -B build
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui -j12
+  #     - name: Build the library (ubuntu latest)
+  #       if: matrix.os == 'ubuntu-latest'
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -DGUI=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DARCH=${{ matrix.arch }} -S . -B build
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer saxs_fitter_gui em_fitter_gui -j12
 
-      - name: Build the library (ubuntu 20.04)
-        if: matrix.os == 'ubuntu-20.04'
-        shell: bash
-        run: |
-          mkdir build
-          cmake -DGUI=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DARCH=${{ matrix.arch }} -S . -B build
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12
+  #     - name: Build the library (ubuntu 20.04)
+  #       if: matrix.os == 'ubuntu-20.04'
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -DGUI=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DARCH=${{ matrix.arch }} -S . -B build
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12
  
-      - name: Build the library (macos)
-        if: matrix.os == 'macos-latest'
-        shell: bash
-        run: |
-          mkdir build
-          cmake -DGUI=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
-                -S . -B build
-          cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12
+  #     - name: Build the library (macos)
+  #       if: matrix.os == 'macos-latest'
+  #       shell: bash
+  #       run: |
+  #         mkdir build
+  #         cmake -DGUI=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
+  #               -S . -B build
+  #         cmake --build build --config $BUILD_TYPE --target ausaxs saxs_fitter em_fitter rigidbody_optimizer -j12
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.os }}-binaries
-          path: |
-            build/lib/*
-            build/bin/*
+  #     - name: Upload artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ${{ matrix.os }}-binaries
+  #         path: |
+  #           build/lib/*
+  #           build/bin/*
       
-      - name: Build tests (ubuntu)
-        if: matrix.os == 'ubuntu-latest'
-        run: cmake --build build --target tests -j ${{ steps.cpu-cores.outputs.count }}
+  #     - name: Build tests (ubuntu)
+  #       if: matrix.os == 'ubuntu-latest'
+  #       run: cmake --build build --target tests -j ${{ steps.cpu-cores.outputs.count }}
 
-      - name: Run tests (ubuntu)
-        if: matrix.os == 'ubuntu-latest'
-        run: ctest --output-on-failure --test-dir build/test
+  #     - name: Run tests (ubuntu)
+  #       if: matrix.os == 'ubuntu-latest'
+  #       run: ctest --output-on-failure --test-dir build/test
 
-      - name: Generate test report (ubuntu)
-        uses: mikepenz/action-junit-report@v4
-        if: matrix.os == 'ubuntu-latest' && (success() || failure())
-        with:
-          report_paths: build/test/reports/*.xml
+  #     - name: Generate test report (ubuntu)
+  #       uses: mikepenz/action-junit-report@v4
+  #       if: matrix.os == 'ubuntu-latest' && (success() || failure())
+  #       with:
+  #         report_paths: build/test/reports/*.xml
 
   test-shared-lib:
     name: Test shared library
-    needs: build
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -171,3 +170,7 @@ jobs:
 
       - name: Test shared library through ctypes
         run: python test/test_shared_lib.py ${PWD}/build
+
+      - name: Check universal binary
+        if: matrix.os == 'macos-latest'
+        run: file build/lib/libausaxs.dylib
