update

diff --git a/.github/workflows/test_sign.yml b/.github/workflows/test_sign.yml
--- a/.github/workflows/test_sign.yml
+++ b/.github/workflows/test_sign.yml
@@ -13,15 +13,6 @@ jobs:
           latest: true
           extract: true
 
-      - name: List extracted artifact
-        run: ls -la macos-universal-binaries
-      
-      - name: List files in bin directory
-        run: ls -la macos-universal-binaries/bin
-      
-      - name: Set executable permissions
-        run: chmod +x macos-universal-binaries/bin/saxs_fitter        
-          
       - name: Sign the artifact
         env: 
           CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE_BASE64 }}
@@ -62,20 +53,20 @@ jobs:
           appstore-connect-team-id: ${{ secrets.MACOS_APP_TEAM_ID }}
           verbose: true
       
-      - name: Staple the notarization ticket
-        run: |
-          # staple the notarization ticket
-          xcrun stapler staple macos-universal-binaries/bin/saxs_fitter
-          # verify the stapling
-          codesign -dv --verbose=4 macos-universal-binaries/bin/saxs_fitter
-          spctl -a -vv macos-universal-binaries/bin/saxs_fitter
-          # check if stapling was successful
-          if spctl -a -vv macos-universal-binaries/bin/saxs_fitter | grep -q "accepted"; then
-            echo "Stapling was successful"
-          else
-            echo "Stapling failed"
-            exit 1
-          fi
+      # - name: Staple the notarization ticket
+      #   run: |
+      #     # staple the notarization ticket
+      #     xcrun stapler staple macos-universal-binaries/bin/saxs_fitter
+      #     # verify the stapling
+      #     codesign -dv --verbose=4 macos-universal-binaries/bin/saxs_fitter
+      #     spctl -a -vv macos-universal-binaries/bin/saxs_fitter
+      #     # check if stapling was successful
+      #     if spctl -a -vv macos-universal-binaries/bin/saxs_fitter | grep -q "accepted"; then
+      #       echo "Stapling was successful"
+      #     else
+      #       echo "Stapling failed"
+      #       exit 1
+      #     fi
 
       - uses: actions/upload-artifact@v4
         with:
